tarefa_criar_resumo_didatico:
  description: >
    Elabore um resumo didático sobre {topic} para alunos iniciantes em tecnologia.
    O texto deve ser escrito em linguagem simples e acolhedora, evitar termos excessivamente
    técnicos (explique quando necessário), usar exemplos práticos e, se possível, analogias
    relacionadas ao dia a dia. Inclua uma breve definição do tema, explique por que ele é
    importante e forneça pelo menos dois exemplos de aplicação prática.
  expected_output: >
    Markdown estruturado, com tópicos bem definidos, linguagem acessível e exemplos práticos.
    Sempre responda em Português (Brasil). Não use marcações de snippets de código no início/fim
    do arquivo de saída, por exemplo ```markdown.
  # Evite usar quebras de linha (multilinha) nos campos abaixo, pois o YAML pode considerar '\n'
  # como parte do valor e isso pode causar problemas em alguns parsers/loaders.
  output_file: "resumo_didatico.md"
  agent: "agente_especialista_didatico"

tarefa_gerar_exercicios:
  description: >
    Crie um conjunto de exercícios práticos sobre {topic} com base no conteúdo do arquivo
    resumo_didatico.md, elaborado para alunos iniciantes em tecnologia. Inclua pelo menos 5
    questões que explorem os principais pontos do resumo, utilizando diferentes formatos, como
    perguntas objetivas, situações problema e desafios de associação. As questões devem ser
    claras, contextualizadas e incentivar o raciocínio prático.
  expected_output: >
    Arquivo em Markdown com pelo menos 5 exercícios variados, bem explicados e adequados para
    iniciantes. Sempre responda em Português (Brasil). Não use marcações de snippets de código
    no início/fim do arquivo de saída, por exemplo ```markdown.
  # Evite usar quebras de linha (multilinha) nos campos abaixo, pois o YAML pode considerar '\n'
  # como parte do valor e isso pode causar problemas em alguns parsers/loaders.
  output_file: "exercicios_praticos.md"
  agent: "agente_criador_exercicios"
